name: Run Infection

on: [push, pull_request]

jobs:
  Infection:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2

      - name: Build the docker-compose stack
        run: docker-compose -f tests/docker-compose.yaml up -d
        env:
          CLICKHOUSE_VERSION: 20

      - name: Install PHP
        uses: shivammathur/setup-php@1.7.0
        with:
          php-version: 7.3
          coverage: xdebug
          extensions: json, mbstring

      - name: Install Dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Run Infection
        run: vendor/bin/infection --min-msi=86 --min-covered-msi=90 --log-verbosity=none -s
        env:
          INFECTION_BADGE_API_KEY: ${{ secrets.INFECTION_BADGE_API_KEY }}
